name: Fetch Weather Data

# Controls when the action will run. Here it runs every 5 minutes.
on:
  schedule:
    - cron: "*/5 * * * *"  # Run every 5 minutes

jobs:
  fetch-weather:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Make an HTTP request to your Vercel API endpoint
    - name: Fetch weather data
      run: |
        curl -X GET "https://weatherstation-six.vercel.app/api/weather?city=Delhi"
